package com.visorcraft.ghostgalleon.rom

/**
 * Slim FBNeo / MAME short-name → display title map so arcade zips are not
 * shown as stems (`mslug`). Not a full DAT. Pure; host-tested.
 */
object ArcadeTitles {

    fun displayName(stem: String): String {
        val key = stem.trim().lowercase()
        if (key.isEmpty()) return stem
        return TITLES[key] ?: stem
    }

    fun knownCount(): Int = TITLES.size

    private val TITLES: Map<String, String> = mapOf(
        "mslug" to "Metal Slug",
        "mslug2" to "Metal Slug 2",
        "mslug3" to "Metal Slug 3",
        "mslug4" to "Metal Slug 4",
        "mslug5" to "Metal Slug 5",
        "mslugx" to "Metal Slug X",
        "sf2" to "Street Fighter II",
        "sf2ce" to "Street Fighter II': Champion Edition",
        "sf2hf" to "Street Fighter II': Hyper Fighting",
        "ssf2" to "Super Street Fighter II",
        "ssf2t" to "Super Street Fighter II Turbo",
        "sfiii3" to "Street Fighter III: 3rd Strike",
        "sfa" to "Street Fighter Alpha",
        "sfa2" to "Street Fighter Alpha 2",
        "sfa3" to "Street Fighter Alpha 3",
        "sfz3mix" to "Street Fighter Zero 3",
        "mvsc" to "Marvel vs. Capcom",
        "mvsc2" to "Marvel vs. Capcom 2",
        "msh" to "Marvel Super Heroes",
        "mshvsf" to "Marvel Super Heroes vs. Street Fighter",
        "xmvsf" to "X-Men vs. Street Fighter",
        "xmcota" to "X-Men: Children of the Atom",
        "kof94" to "The King of Fighters '94",
        "kof95" to "The King of Fighters '95",
        "kof96" to "The King of Fighters '96",
        "kof97" to "The King of Fighters '97",
        "kof98" to "The King of Fighters '98",
        "kof99" to "The King of Fighters '99",
        "kof2000" to "The King of Fighters 2000",
        "kof2001" to "The King of Fighters 2001",
        "kof2002" to "The King of Fighters 2002",
        "kof2003" to "The King of Fighters 2003",
        "samsho" to "Samurai Shodown",
        "samsho2" to "Samurai Shodown II",
        "lastblad" to "The Last Blade",
        "lastbld2" to "The Last Blade 2",
        "garou" to "Garou: Mark of the Wolves",
        "fatfury1" to "Fatal Fury",
        "fatfury2" to "Fatal Fury 2",
        "fatfury3" to "Fatal Fury 3",
        "rbff1" to "Real Bout Fatal Fury",
        "rbff2" to "Real Bout Fatal Fury 2",
        "rbffspec" to "Real Bout Fatal Fury Special",
        "dino" to "Cadillacs and Dinosaurs",
        "punisher" to "The Punisher",
        "knights" to "Knights of the Round",
        "ffight" to "Final Fight",
        "captcomm" to "Captain Commando",
        "varth" to "Varth: Operation Thunderstorm",
        "1941" to "1941: Counter Attack",
        "1942" to "1942",
        "1943" to "1943: The Battle of Midway",
        "1944" to "1944: The Loop Master",
        "19xx" to "19XX: The War Against Destiny",
        "ghouls" to "Ghouls 'n Ghosts",
        "mtwins" to "Mega Twins",
        "strider" to "Strider",
        "willow" to "Willow",
        "unsquad" to "U.N. Squadron",
        "area88" to "Area 88",
        "mercs" to "Mercs",
        "wof" to "Warriors of Fate",
        "dynwar" to "Dynasty Wars",
        "kod" to "The King of Dragons",
        "3wonders" to "Three Wonders",
        "cawing" to "Carrier Air Wing",
        "forgottn" to "Forgotten Worlds",
        "nemo" to "Nemo",
        "pang" to "Pang",
        "spang" to "Super Pang",
        "block" to "Block Block",
        "pang3" to "Pang! 3",
        "ssideki" to "Super Sidekicks",
        "ssideki2" to "Super Sidekicks 2",
        "socbrawl" to "Soccer Brawl",
        "turfmast" to "Neo Turf Masters",
        "pbobblen" to "Puzzle Bobble",
        "pbobbl2n" to "Puzzle Bobble 2",
        "magdrop3" to "Magical Drop III",
        "breakers" to "Breakers",
        "breakrev" to "Breakers Revenge",
        "whp" to "World Heroes Perfect",
        "wh1" to "World Heroes",
        "wh2" to "World Heroes 2",
        "aof" to "Art of Fighting",
        "aof2" to "Art of Fighting 2",
        "aof3" to "Art of Fighting 3",
        "doubledr" to "Double Dragon",
        "irrmaze" to "The Irritating Maze",
        "neobombe" to "Neo Bomberman",
        "shocktr2" to "Shock Troopers 2nd Squad",
        "shocktro" to "Shock Troopers",
        "blazstar" to "Blazing Star",
        "pulstar" to "Pulstar",
        "preisle2" to "Prehistoric Isle 2",
        "sengoku" to "Sengoku",
        "sengoku2" to "Sengoku 2",
        "sengoku3" to "Sengoku 3",
        "viewpoin" to "Viewpoint",
        "androdun" to "Andro Dunos",
        "alpham2" to "Alpha Mission II",
        "lbowling" to "League Bowling",
        "ncommand" to "Ninja Commando",
        "ncombat" to "Ninja Combat",
        "crsword" to "Crossed Swords",
        "roboarmy" to "Robo Army",
        "kotm" to "King of the Monsters",
        "kotm2" to "King of the Monsters 2",
        "bstars" to "Baseball Stars Professional",
        "bstars2" to "Baseball Stars 2",
        "tophuntr" to "Top Hunter",
        "spinmast" to "Spinmaster",
        "zedblade" to "Zed Blade",
        "sonicwi2" to "Aero Fighters 2",
        "sonicwi3" to "Aero Fighters 3",
        "twinspri" to "Twinkle Star Sprites",
        "ganryu" to "Ganryu",
        "bangbead" to "Bang Bead",
        "pnyaa" to "Pochi and Nyaa",
        "jockeygp" to "Jockey Grand Prix",
        "rotd" to "Rage of the Dragons",
        "matrim" to "Power Instinct Matrimelee",
        "svc" to "SNK vs. Capcom: SVC Chaos",
        "samsho3" to "Samurai Shodown III",
        "samsho4" to "Samurai Shodown IV",
        "samsho5" to "Samurai Shodown V",
        "samsh5sp" to "Samurai Shodown V Special",
        "pacman" to "Pac-Man",
        "mspacman" to "Ms. Pac-Man",
        "galaga" to "Galaga",
        "galaxian" to "Galaxian",
        "dkong" to "Donkey Kong",
        "dkongjr" to "Donkey Kong Jr.",
        "dkong3" to "Donkey Kong 3",
        "mario" to "Mario Bros.",
        "invaders" to "Space Invaders",
        "centiped" to "Centipede",
        "missile" to "Missile Command",
        "asteroid" to "Asteroids",
        "tempest" to "Tempest",
        "qbert" to "Q*bert",
        "joust" to "Joust",
        "robotron" to "Robotron: 2084",
        "defender" to "Defender",
        "stargate" to "Stargate",
        "frogger" to "Frogger",
        "digdug" to "Dig Dug",
        "xevious" to "Xevious",
        "outrun" to "Out Run",
        "orunners" to "OutRunners",
        "goldnaxe" to "Golden Axe",
        "altbeast" to "Altered Beast",
        "shinobi" to "Shinobi",
        "aliensyn" to "Alien Syndrome",
        "tetris" to "Tetris",
        "columns" to "Columns",
        "sonic" to "SegaSonic the Hedgehog",
        "bublbobl" to "Bubble Bobble",
        "bublbob2" to "Bubble Symphony",
        "rainbow" to "Rainbow Islands",
        "rastan" to "Rastan",
        "darius" to "Darius",
        "dariusg" to "Darius Gaiden",
        "chasehq" to "Chase H.Q.",
        "sciclone" to "Special Criminal Investigation",
        "opwolf" to "Operation Wolf",
        "volvfyra" to "Operation Thunderbolt",
        "elevator" to "Elevator Action",
        "bublboblp" to "Bubble Bobble",
        "simpsons" to "The Simpsons",
        "tmnt" to "Teenage Mutant Ninja Turtles",
        "tmnt2" to "Teenage Mutant Ninja Turtles: Turtles in Time",
        "xmen" to "X-Men",
        "vendetta" to "Vendetta",
        "crimfght" to "Crime Fighters",
        "aliens" to "Aliens",
        "crimec" to "Crime City",
        "bucky" to "Bucky O'Hare",
        "mia" to "M.I.A.",
        "hcastle" to "Haunted Castle",
        "gradius" to "Gradius",
        "gradius3" to "Gradius III",
        "salamand" to "Salamander",
        "lifeofc" to "The Life of a Cowboy",
        "neogeo" to "Neo Geo BIOS",
        "ngbios" to "Neo Geo BIOS",
        "mk" to "Mortal Kombat",
        "mk2" to "Mortal Kombat II",
        "mk3" to "Mortal Kombat 3",
        "umk3" to "Ultimate Mortal Kombat 3",
        "mk4" to "Mortal Kombat 4",
        "nbajam" to "NBA Jam",
        "nbajamte" to "NBA Jam Tournament Edition",
        "smashtv" to "Smash T.V.",
        "narc" to "NARC",
        "term2" to "Terminator 2: Judgment Day",
        "gauntlet" to "Gauntlet",
        "gaunt2" to "Gauntlet II",
        "paperboy" to "Paperboy",
        "spyhunt" to "Spy Hunter",
        "rampage" to "Rampage",
        "rampart" to "Rampart",
        "toobin" to "Toobin'",
        "klax" to "Klax",
        "tron" to "Tron",
        "joust2" to "Joust 2",
        "sinistar" to "Sinistar",
        "starwars" to "Star Wars",
        "esb" to "The Empire Strikes Back",
        "polepos" to "Pole Position",
        "polepos2" to "Pole Position II",
        "hangon" to "Hang-On",
        "shangon" to "Super Hang-On",
        "aburner" to "After Burner",
        "aburner2" to "After Burner II",
        "thndrbld" to "Thunder Blade",
        "gng" to "Ghosts 'n Goblins",
        "avsp" to "Alien vs. Predator",
        "armwar" to "Armored Warriors",
        "batcir" to "Battle Circuit",
        "cybots" to "Cyberbots",
        "dstlk" to "Darkstalkers",
        "nwarr" to "Night Warriors",
        "vsav" to "Vampire Savior",
        "hsf2" to "Hyper Street Fighter II",
        "ddtod" to "Dungeons & Dragons: Tower of Doom",
        "ddsom" to "Dungeons & Dragons: Shadow over Mystara",
        "megaman" to "Mega Man: The Power Battle",
        "megaman2" to "Mega Man 2: The Power Fighters",
        "progear" to "Progear",
        "dimahoo" to "Dimahoo",
        "ddonpach" to "DoDonPachi",
        "donpachi" to "DonPachi",
        "espgal" to "Espgaluda",
        "guwange" to "Guwange",
        "batsugun" to "Batsugun",
        "truxton" to "Truxton",
        "outzone" to "Out Zone",
        "snowbro" to "Snow Bros.",
        "snowbro2" to "Snow Bros. 2",
        "cabal" to "Cabal",
        "bloodbro" to "Blood Bros.",
        "cninja" to "Caveman Ninja",
        "robocop" to "Robocop",
        "midres" to "Midnight Resistance",
    )
}
